<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <link name="base_link"/>
    <link name="base_footprint"/>
    <link name="chassis">
        <visual>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
            </geometry>
            <origin xyz="0 0 ${chassis_height / 2.0}" rpy="0 0 0" />
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
            </geometry>
        </collision>
        <xacro:box_inertia m="5.0" l="${chassis_length}" w="${chassis_width}" h="${chassis_height}"
                    xyz="0 0 ${chassis_height / 2.0}" rpy="0 0 0" />
    </link>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <joint name="base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0 0 ${wheel_radius/2}" rpy="0 0 0"/>
    </joint>
</robot>
