<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <joint name="laser_joint" type="fixed">
        <parent link="chassis"/>
        <child link="laser_frame"/>
        <origin xyz="0 0 ${9 / 8 * chassis_height }" rpy="0 0 0"/>

    </joint>

    <link name="laser_frame">
        <visual> 
            <geometry>
                <cylinder radius="${chassis_width / 4}" length="${chassis_height / 4}"/>
            </geometry>
            <material name="green"/>
        </visual>
        <collision> 
            <geometry>
                <cylinder radius="${chassis_width / 4}" length="${chassis_height / 4}"/>
            </geometry>
            <material name="green"/>
        </collision>
        <xacro:cylinder_inertia m="1.0" r="${chassis_width / 4}" h="${chassis_height / 4}" xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
    </link>

</robot>